### ISSUE TITLE
Lifetime of symbols

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/isla#21]
As I mentioned in #16, my first intuition for the lifetime of a symbol was this:

- a symbol gets created by a read from an uninitialized/volatile source
- as long as that symbol is on the executor's current stack or inside a register (or in an rw memory region if you implement that), it does not go "out of scope" (meaning it stays in the trace and z3's world of things)
- derivated symbols may be created by having a computation of the symbol with another symbol, an immediate value, or itself
- the symbol must not go "out of scope" until all derivated symbols (and their derivatives) have gone "out of scope"
- if a symbol goes "out of scope", it has no further burden on the execution, meaning all corresponding memory is freed and it is removed from z3's world of things

but I fear your hashmaps (`decls`, `func_decls`, `enum_map`) are indefinitely storing the symbols. Is that correct, and would you agree that "cleaning" the hashmaps' symbol graphs of dead branches should be possible?

**Comment by Alasdair** [comment]
Symbols are just identifiers for named Z3 expressions. They are not references so they do not have lifetimes in the strict rust-specific sense of the term, but conceptually they are linked to a `Solver`. However they remain valid if you make a `Checkpoint` from a `Solver` and then replay that checkpoint to create a new solver. The setup is defined to mimic the SMTLIB input format used by Z3 and other SMT solvers, so:

```
(define-const x some-z3-expression)
                      ^ This identifier 'x' is what we call a symbol
```

The only reason I used the term `Sym`/symbol is because I was already using `Id`/identifier for Sail identifiers and it helps to make them more obviously separate. Obviously if you try using 'x' in some other SMT problem then it might not correspond to anything, or may be some completely different expression. Internally there is a tree representing the SMT problem corresponding to the branching structure of the program, and anything we have fully explored is immutable while each leaf of the tree is owned by a currently executing task that is exploring that specific branch. As those tasks complete, branches of the tree that are no-longer associated with any task will be automatically freed.

To explain the checkpoints some more: Nothing related to Z3 can be safely moved between threads, once we create a Solver it's locked to a specific thread, so when we want to branch/fork and create a new task it gets a new Solver which is recreated from scratch by replaying the SMT commands from the root of the tree up until the branch point.

> but I fear your hashmaps (decls, func_decls, enum_map) are indefinitely storing the symbols. Is that correct, and would you agree that "cleaning" the hashmaps' symbol graphs of dead branches should be possible?

As each branch has it's own solver instance, when they're finished the solver is dropped and the memory is freed. All the Z3 types have custom drop instances that handle the reference count bookkeeping for Z3. I have checked with valgrind to ensure we are not leaking memory (mostly because working with the Z3 C API is finnicky, it's pretty hard to accidentally leak memory in Rust unless you abuse Rc/Arc to create reference cycles or similar).

**Comment by Trolldemorted** [comment]
>As each branch has it's own solver instance, when they're finished the solver is dropped and the memory is freed. All the Z3 types have custom drop instances that handle the reference count bookkeeping for Z3. I have checked with valgrind to ensure we are not leaking memory (mostly because working with the Z3 C API is finnicky, it's pretty hard to accidentally leak memory in Rust unless you abuse Rc/Arc to create reference cycles or similar).

Sorry for using overloaded terminology, I didn't mean "rust lifetimes", but "conceptual lifetimes". Let's say we are executing Step_CPU 3 times with this bytecode:
```
MOV X1, 0x1000  // (1) move an uninitialized memory location into X1
LSR X1, X1, 1   // (2) left shit X1
MOV X1, 0x2000  // (3) move another uninitialized memory location into X1
```

After (1), there is a symbol (s1) in X1. The checkpoint/trace contains a `Def::DeclareConst` for s1.

After (2), there is a new symbol (s2) in X1. The checkpoint/trace contains a `Def::DeclareConst` for s1 and a `Def::DefineConst(Exp::Bvshl(...), Box::new(1))` for s2.

After (3), there is another new symbol (s3) in X1. The checkpoint/trace contains a `Def::DeclareConst` for s1, a `Def::DefineConst(Exp::Bvshl(...), Box::new(1))` for s2, and a `Def::DeclareConst` for s3.

If I understand the current implementation correctly, the definitions for s1 and s2 will be in the trace forever, and decls, func_decls, and enum_map will forever contain the symbols' ids. However you would agree that this is preventable, because
- s1 knows it has no parents
- s2 knows it has the parent s1
- as soon as X1 holds s3, a ref-counted implementation of s2 would notice that it is no longer needed
- as soon as s2 is disposed, s1 would notice that it is no longer needed

For long running scenarios the accumulation is detrimental for performance, because traces get bigger with every step, the hashmaps' performance degrades as they grow fuller, and the replay fills z3 with a lot of information it evidentially does not need.




>To explain the checkpoints some more: Nothing related to Z3 can be safely moved between threads, once we create a Solver it's locked to a specific thread

I was wondering about the thread safety of z3 too and [asked them](https://github.com/Z3Prover/z3/issues/4762): It is safe if you move everything (context, solver, asts, ...) to the same thread (they also updated their [documentation](https://github.com/Z3Prover/z3/blob/master/src/api/z3_api.h#L1587) about that). I am wondering whether this can be [safely integrated into z3.rs](https://github.com/prove-rs/z3.rs/issues/100), because right now their types are `!Send`. Were there specific reasons you chose z3-sys over their high-level bindings? At a quick glance they don't look too bad.

**Comment by Trolldemorted** [comment]
>I think those types have to be !Send because of the additional requirements you mention. You could do it with unsafe rust.

Yep I have sent them a proposal how things could be done, let's see what they make of it.

>I have done profiling and the performance costs of checking satisfiability outweigh pretty much everything else. I think that most of the performance costs with this structure are caused by lots of memory allocation, so I have thought about using an arena allocator for traces, although that would be even more memory hungry.

My assumption is that this depends a lot on the code you are examining. While emulating my current firmware I am executing `zStep_CPU` a few hundred times, and `Solver::from_checkpoint` is consistently taking up 2/3 of the time spent during each step (after about 1k steps each step takes ~2.7s, and each from_checkpoint takes ~1.8s). I think it is also fair to assume that sat checks will perform better if less variables are pushed into the context.

>For my use case I don't throw away any intermediate steps because I might need it to calculate instruction address, data, and control dependencies for the concurrency model. For larger symbolic analysis tasks our approach has been to generate traces for basic blocks and single instructions, and then simplify the traces after the fact, rather than using a reference counting scheme during execution.

Yeah, I know, that's why wanted to talk about it - do you think it would be a good idea for isla-lib to separate the indefinite tracking from the the executor in a way that it becomes optional? Consolidating the effects of basic blocks must be done for larger systems eventually, but I firmly believe we can push the threshold at which it has to be done significantly farther away.

**Comment by Trolldemorted** [comment]
I have migrated to going through your traces, and do the symbol lifetime management outside of isla-lib
